name: Trigger auto deployment for container-app-kena4kducrole

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-kena4kducrole-AutoDeployTrigger-d607bfef-ff00-4915-b4b3-3a17b79bae9c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPKENA4KDUCROLE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPKENA4KDUCROLE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPKENA4KDUCROLE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPKENA4KDUCROLE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPKENA4KDUCROLE_REGISTRY_PASSWORD }}
          containerAppName: container-app-kena4kducrole
          resourceGroup: appspacesragappa02f86ce
          imageToBuild: default/container-app-kena4kducrole:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


